# 测试相关
test_num: 100                             # 评测 episode 数量
sample: 0                                 # 样本索引
rnd: false                                # 是否启用随机采样，false 表示使用sample的样本
restore: true                             # 是否启用断点续测

# 部署相关
stage: 2                                  # 测试阶段 OBS=0, SKIP, FULL
use_cpp: true                             # 是否仅使用端侧推理，仿真侧不执行推理（stage为FULL时可选）
torch_model: "/mnt/data/llm_model_zoo/pi0/pi05_aloha_pytorch_hammer_0310"
                                          # PyTorch 模型路径
port: 30001                               # 监听socket连接的端口

# 滤波相关
filter: 0                                 # 滤波类型：0，禁用；1：ButterWorth；2：FIR；3：ZeroPhase
cutoff: 3                                 # 截止频率
fs: 50                                    # 采样频率
channels: 14                              # 滤波维度

# 推理相关
chunk: 50                                 # 每輪使用的chunk_size(max=50)
visp: false                               # 使用vispruner词汇压缩
do_preproc: false                         # 发送预处理后的OBS
do_postproc: false                        # 对ACTION后处理
debug: false

# 显示相关
use_video: true                           # 是否保存视频
save_frame: false                         # 是否保存原始 obs 到录像目录（每 episode 一个文件夹）
save_all_frames: false                    # false: 仅保存推理帧；true: 保存仿真每一步的 obs
spcam: false                              # 是否使用自定义camera，在_camera_config.yaml调整分辨率，在eval_policy.py中调整角度
raw_tri: false
cat_dim: 1                                # 拼接维度：0 竖拼，1 横拼
fresh: 0                                  # 图像刷新时间，0为不显示图像
hd: 2                                     # 图像放大倍数
