# 测试相关
test_num: 100                             # 评测 episode 数量
sample: 0                                 # 样本索引
rnd: true                                 # 是否启用随机采样，false 表示使用sample的样本
save_sample: true                         # rnd=true时是否保存随机采样的样本指令
restore: false                            # 是否启用断点续测

# 部署相关
stage: 2                                  # 推理阶段：OBS=0（观测回环测试），LOCAL=1（本地推理），NETWORK=2（远程推理）
remote_action: true                       # 是否用 remote 的 action 进行 step（stage=NETWORK时生效；true=用remote action，false=用local action）
local_model: false                        # 是否加载本地模型（stage=NETWORK时生效；true=加载本地模型，false=不加载；stage=LOCAL/OBS时强制加载）
torch_model: "/mnt/data2/llm_model_zoo/pi0/pi05_aloha_pytorch_hammer_0310"
                                          # PyTorch 模型路径
port: 30005                               # 监听socket连接的端口

# 滤波相关
filter: 0                                 # 滤波类型：0，禁用；1：ButterWorth；2：FIR；3：ZeroPhase
cutoff: 3                                 # 截止频率
fs: 50                                    # 采样频率
channels: 14                              # 滤波维度

# 推理相关
chunk: 50                                 # 每轮使用的chunk_size(max=50)
visp: false                               # 使用vispruner词汇压缩
do_preproc: false                         # 发送预处理后的OBS
do_postproc: false                        # 对远端ACTION后处理
debug: false

# 显示相关
use_video: true                           # 是否保存视频
save_frame: false                         # 是否保存原始 obs 到录像目录（每 episode 一个文件夹）
save_all_frames: false                    # false: 仅保存推理帧；true: 保存仿真每一步的 obs
spcam: false                              # 是否使用自定义camera，在_camera_config.yaml调整分辨率，在eval_policy.py中调整角度
hd: 2                                     # 图像放大倍数（eval_policy video_size 计算）
