# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: msg.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()

# flake8: noqa: F821
# flake8: noqa: E501
# flake8: noqa: E712

DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tmsg.proto\x12\x00"!\n\x04Time\x12\x0b\n\x03sec\x18\x01 \x01(\x03\x12\x0c\n\x04nsec\x18\x02 \x01(\x05"m\n\x06Header\x12\x0b\n\x03seq\x18\x01 \x01(\r\x12\x14\n\x05stamp\x18\x02 \x01(\x0b2\x05.Time\x12\x10\n\x08frame_id\x18\x03 \x01(\t\x12\x0c\n\x04type\x18\x04 \x01(\r\x12\r\n\x05reset\x18\x05 \x01(\x08\x12\x11\n\tview_only\x18\x06 \x01(\x08"\x98\x01\n\x06Tensor\x12\x1f\n\x05dtype\x18\x01 \x01(\x0e2\x10.Tensor.DataType\x12\r\n\x05shape\x18\x02 \x03(\x05\x12\x0c\n\x04data\x18\x03 \x01(\x0c"P\n\x08DataType\x12\x0b\n\x07FLOAT64\x10\x00\x12\t\n\x05UINT8\x10\x01\x12\n\n\x06STRING\x10\x02\x12\x0b\n\x07FLOAT32\x10\x03\x12\t\n\x05INT32\x10\x04\x12\x08\n\x04FP16\x10\x05"x\n\x0fMultiModalInput\x12\x17\n\x06header\x18\x01 \x01(\x0b2\x07.Header\x12\x17\n\x06images\x18\x02 \x03(\x0b2\x07.Tensor\x12\x1a\n\tlanguages\x18\x03 \x03(\x0b2\x07.Tensor\x12\x17\n\x06states\x18\x04 \x03(\x0b2\x07.Tensorb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'msg_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _TIME._serialized_start=13
  _TIME._serialized_end=46
  _HEADER._serialized_start=48
  _HEADER._serialized_end=139
  _TENSOR._serialized_start=142
  _TENSOR._serialized_end=294
  _TENSOR_DATATYPE._serialized_start=214
  _TENSOR_DATATYPE._serialized_end=294
  _MULTIMODALINPUT._serialized_start=296
  _MULTIMODALINPUT._serialized_end=416
# @@protoc_insertion_point(module_scope)
